name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: '**/pom.xml'

    - name: Build with Maven
      working-directory: demo-java-app
      run: mvn clean package --file pom.xml

    - name: Run Tests
      working-directory: demo-java-app
      run: mvn test

    # - name: Upload Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: demo-java-app-war
    #     path: demo-java-app/target/*.war
